#
# Choose your platform to be able to compile easily with just
# the "make" command without specifying specific makefile
#

include linux.mak
#include djgpp.mak
#include mingw.mak
#include watcom.mak


